# Generated by Django 3.1.1 on 2021-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210623_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactagent',
            name='email',
            field=models.EmailField(default='dummyemail@yahoo.com', max_length=254),
            preserve_default=False,
        ),
    ]
